#!/usr/bin/env python3

import json
from TimerBot.Bot import Bot

with open("config.json") as cfgfile:
    cfgfile = cfgfile.readlines()

config = ""
for i in cfgfile:
	config += i

del cfgfile, i

bot = Bot(json.loads(config))

del config

bot.run()
